In [4]:
import numpy as np
import pandas as pd

### Creating a DataFrame

In [ ]:
''' We can create a datframe via Series , Dictionary '''

In [8]:
data = {
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [25, 30, 28, 35],
    "city": ["Bangalore", "Mumbai", "Delhi", "Chennai"],
    "salary": [50000, 60000, 55000, 70000]
}
df = pd.DataFrame(data)

In [9]:
df

      name  age       city  salary
0    Alice   25  Bangalore   50000
1      Bob   30     Mumbai   60000
2  Charlie   28      Delhi   55000
3    David   35    Chennai   70000

In [15]:
data_list = [
    ["Alice", 25, "Bangalore", 50000],
    ["Bob", 30, "Mumbai", 60000],
    ["Charlie", 28, "Delhi", 55000],
    ["David", 35, "Chennai", 70000]
]
df2 = pd.DataFrame(data_list)

In [16]:
df2

         0   1          2      3
0    Alice  25  Bangalore  50000
1      Bob  30     Mumbai  60000
2  Charlie  28      Delhi  55000
3    David  35    Chennai  70000

In [26]:
data_list = [
    ["Alice", 25, "Bangalore", 50000],
    ["Bob", 30, "Mumbai", 60000],
    ["Charlie", 28, "Delhi", 55000],
    ["David", 35, "Chennai", 70000]
]
df2 = pd.DataFrame(data_list)
colums = ['name','age','city','salary']
df2= pd.DataFrame(data_list,columns = colums)

In [19]:
df2

      name  age       city  salary
0    Alice   25  Bangalore   50000
1      Bob   30     Mumbai   60000
2  Charlie   28      Delhi   55000
3    David   35    Chennai   70000

###  Selection and Indexing of Columns

In [ ]:
''' In DataFrame , the index doesn't work but the Columns values , we have to write Labels '''

In [20]:
df2['name']

0      Alice
1        Bob
2    Charlie
3      David
Name: name, dtype: object

In [21]:
'''If I want to target more than two columns then we have to create list inside list'''

'If I want to target more than two columns then we have to create list inside list'

In [27]:
df2[['name','city']]

      name       city
0    Alice  Bangalore
1      Bob     Mumbai
2  Charlie      Delhi
3    David    Chennai

### Creating a new Column

In [28]:
''' To add a new columns inside a Data Frame but while assigning value  take care we fill the required no. '''
df2['role']= ['Intern', 'Associate', 'Developer' , 'Associate']

In [24]:
df2

      name  age       city  salary       role
0    Alice   25  Bangalore   50000     Intern
1      Bob   30     Mumbai   60000  Associate
2  Charlie   28      Delhi   55000  Developer
3    David   35    Chennai   70000  Associate

### Removing Columns

In [29]:
df2.drop('role',axis = 1)
'''This will not remove the data permanently or we have to use someplace to store this removed data and reassign it to df2 '''

'This will not remove the data permanently or we have to use someplace to store this removed data and reassign it to df2 '

In [30]:
df2

      name  age       city  salary       role
0    Alice   25  Bangalore   50000     Intern
1      Bob   30     Mumbai   60000  Associate
2  Charlie   28      Delhi   55000  Developer
3    David   35    Chennai   70000  Associate

In [31]:
df2.drop('role',axis=1,inplace = True)
''' This will remove the data permanently  '''

' This will remove the data permanently  '

In [32]:
df2

      name  age       city  salary
0    Alice   25  Bangalore   50000
1      Bob   30     Mumbai   60000
2  Charlie   28      Delhi   55000
3    David   35    Chennai   70000

In [34]:
df2.drop(['city','salary'],axis=1)

      name  age
0    Alice   25
1      Bob   30
2  Charlie   28
3    David   35

In [35]:
''' If we want to remove the row ,then we have to make axis =0 '''
df2.drop(0,axis=0)

      name  age     city  salary
1      Bob   30   Mumbai   60000
2  Charlie   28    Delhi   55000
3    David   35  Chennai   70000

### Selectings Rows

In [36]:
df2.loc[0]

name          Alice
age              25
city      Bangalore
salary        50000
Name: 0, dtype: object

In [39]:
''' Helps selecting row using Labels / Names '''
df2.loc[[0,2]]

      name  age       city  salary
0    Alice   25  Bangalore   50000
2  Charlie   28      Delhi   55000

In [40]:
''' Helps selecting row using  Integer Positions '''
df2.iloc[3]

name        David
age            35
city      Chennai
salary      70000
Name: 3, dtype: object

### Selecting Subsets of Rows and Columns

In [43]:
df2.loc[[0,1]][['city','salary']]

        city  salary
0  Bangalore   50000
1     Mumbai   60000

In [45]:
df2.loc[[2,3]][['name','city']]

      name     city
2  Charlie    Delhi
3    David  Chennai

### Conditional Selection

In [46]:
df2

      name  age       city  salary
0    Alice   25  Bangalore   50000
1      Bob   30     Mumbai   60000
2  Charlie   28      Delhi   55000
3    David   35    Chennai   70000

In [53]:
''' Show people whose age is above 30 '''

df2[df2['age']>30]

    name  age     city  salary
3  David   35  Chennai   70000

In [54]:
df2[df2.iloc[:,1]>30]

    name  age     city  salary
3  David   35  Chennai   70000

In [64]:
''' Show people whose age is above 30 and city is Chennai '''
df2[(df2.iloc[:,1]>30 )& (df2.iloc[:,2]=='Chennai')]

    name  age     city  salary
3  David   35  Chennai   70000

In [60]:
df2[(df2['age']>30 )& (df2['city'] == 'Chennai')]

    name  age     city  salary
3  David   35  Chennai   70000