In [4]:
import numpy as np
import pandas as pd

#### Finding Missing Data

In [21]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [22]:
''' to check how many Null Values are there'''
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [23]:
'''For each label/column , we check total count of Null Value'''
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [24]:
'to check for each columns do we any missing value  '
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

#### Removing Missing Data

In [25]:
''' Removing Data works on Rows basis '''
df

     A  B    C    D
0  1.0  5  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [26]:
''' To remove rows that contain at least one NULL/NaN value (it will not remove the row which don't have any NULL Values') '''
df.dropna()

     A  B    C    D
0  1.0  5  1.0  1.0

In [27]:
df

     A  B    C    D
0  1.0  5  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [30]:
''' thresh specifies the minimum number of non-null values required in each row .Rows with at least the specified number of non-null values are retained. '''
df.dropna(thresh = 3)

     A  B    C    D
0  1.0  5  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [32]:
df.dropna(thresh = 4)

     A  B    C    D
0  1.0  5  1.0  1.0

In [33]:
df.dropna(thresh = 5)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

#### Filling the missing Data

In [34]:
df

     A  B    C    D
0  1.0  5  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [35]:
''' It makes sure that all the Null value are filled by X value.'''
df.fillna(0)

     A  B    C    D
0  1.0  5  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [38]:
''' until and unless we write ( inplace = True ) ,No Changes will be made '''
df.fillna(11)

      A  B     C     D
0   1.0  5   1.0   1.0
1   2.0  2   2.0  11.0
2  11.0  3   3.0  11.0
3   4.0  4  11.0  11.0
4   5.0  5  11.0   5.0

In [39]:
df

     A  B    C    D
0  1.0  5  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [41]:
''' if for each columns we want to fill Null places by given value , '''

random_val = {'A':0,'B':120,'C':820,'D':970}
df.fillna(value= random_val)

     A  B      C      D
0  1.0  5    1.0    1.0
1  2.0  2    2.0  970.0
2  0.0  3    3.0  970.0
3  4.0  4  820.0  970.0
4  5.0  5  820.0    5.0

##### dropna() => works ROW wise
##### fillna() => works COLUMNS wise

In [42]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  5  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0